
CREATE TABLE public.cfg_setting (
    name VARCHAR(64) NOT NULL PRIMARY KEY,
    value VARCHAR(64) NULL
);

CREATE TABLE public.cfg_user_role (
    cfg_user_role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL
);

CREATE TABLE public.cfg_make (
    cfg_make_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    name VARCHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL
);

CREATE TABLE public.cfg_model (
    cfg_model_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    cfg_make_id INT,
    name VARCHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL,

    CONSTRAINT fk_model__make FOREIGN KEY(cfg_make_id) REFERENCES cfg_make(cfg_make_id)
);

CREATE TABLE public.app_user (
    app_user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by INT NOT NULL,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(64) NULL,
    password_attempt_count INT NOT NULL DEFAULT 0,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    locked_at TIMESTAMPTZ NULL,
    phone VARCHAR(20) NULL,
    email VARCHAR(64) NULL UNIQUE,
    cfg_user_role_id INT NOT NULL
);

CREATE TABLE public.vehicle (
    vehicle_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    updated_by INT NOT NULL,
    app_user_id INT NOT NULL,
    make VARCHAR(32) NOT NULL,
    model VARCHAR(32) NOT NULL,
    year SMALLINT NOT NULL,
    color VARCHAR(32) NOT NULL,
    vin CHAR(17) NULL UNIQUE,
    license_plate VARCHAR(15) NULL UNIQUE,

    CONSTRAINT fk_vehicle__app_user FOREIGN KEY(app_user_id) REFERENCES app_user(app_user_id)
);
